const express = require('express');
const { getDb } = require('../db/database');
const { authenticateToken } = require('../middleware/auth');
const { generateId, now } = require('../utils/helpers');

const router = express.Router();
router.use(authenticateToken);

// 技能
router.get('/abilities', (req, res) => {
  try {
    const db = getDb();
    const abilities = db.prepare('SELECT * FROM athena_abilities WHERE user_id = ? ORDER BY created_at DESC').all(req.user.id);
    res.json({ abilities });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

router.post('/abilities', (req, res) => {
  try {
    const { name, description, autoGenerated } = req.body;
    if (!name) return res.status(400).json({ error: '技能名称不能为空' });
    const db = getDb();
    const id = generateId();
    db.prepare('INSERT INTO athena_abilities (id, user_id, name, description, auto_generated, created_at) VALUES (?, ?, ?, ?, ?, ?)').run(id, req.user.id, name, description || '', autoGenerated ? 1 : 0, now());
    res.status(201).json({ ability: { id, name, description, autoGenerated: !!autoGenerated } });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

router.delete('/abilities/:id', (req, res) => {
  try {
    const db = getDb();
    db.prepare('DELETE FROM athena_abilities WHERE id = ? AND user_id = ?').run(req.params.id, req.user.id);
    res.json({ message: '删除成功' });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

// 记忆
router.get('/memories', (req, res) => {
  try {
    const db = getDb();
    const memories = db.prepare('SELECT * FROM athena_memories WHERE user_id = ? ORDER BY created_at DESC').all(req.user.id);
    res.json({ memories });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

router.post('/memories', (req, res) => {
  try {
    const { type, category, content } = req.body;
    if (!type || !content) return res.status(400).json({ error: '参数不完整' });
    const db = getDb();
    const id = generateId();
    const timestamp = now();
    db.prepare('INSERT INTO athena_memories (id, user_id, type, category, content, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(id, req.user.id, type, category || '', content, timestamp, timestamp);
    res.status(201).json({ memory: { id, type, category: category || '', content } });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

router.put('/memories/:id', (req, res) => {
  try {
    const { content, category } = req.body;
    const db = getDb();
    if (content !== undefined) db.prepare('UPDATE athena_memories SET content = ?, updated_at = ? WHERE id = ? AND user_id = ?').run(content, now(), req.params.id, req.user.id);
    if (category !== undefined) db.prepare('UPDATE athena_memories SET category = ?, updated_at = ? WHERE id = ? AND user_id = ?').run(category, now(), req.params.id, req.user.id);
    res.json({ message: '更新成功' });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

router.delete('/memories/:id', (req, res) => {
  try {
    const db = getDb();
    db.prepare('DELETE FROM athena_memories WHERE id = ? AND user_id = ?').run(req.params.id, req.user.id);
    res.json({ message: '删除成功' });
  } catch (err) {
    res.status(500).json({ error: '服务器内部错误' });
  }
});

module.exports = router;
