// ===== 核心类型定义 =====

/** 考点优先级 */
export type Priority = 'must' | 'high' | 'know'

/** 课程状态 */
export type CourseStatus = 'empty' | 'uploaded' | 'analyzing' | 'ready'

/** 关卡状态 */
export type LessonStatus = 'locked' | 'available' | 'in-progress' | 'completed'

/** 课件文件类型 */
export interface CourseFile {
  id: string
  name: string
  path: string
  ext: string
  size: number
  uploadedAt: number
}

/** 课程 */
export interface Course {
  id: string
  name: string
  files: CourseFile[]
  status: CourseStatus
  examDate?: string
  createdAt: number
  updatedAt: number
}

/** 考点 */
export interface ExamPoint {
  id: string
  title: string
  priority: Priority
  description: string
  keyFormulas?: string[]
  examples?: string[]
  pageRefs?: string[]
  /** 来源文件名 */
  sourceFile?: string
}

/** 关卡（学习单元） */
export interface Lesson {
  id: string
  courseId: string
  order: number
  title: string
  examPointId: string
  priority: Priority
  status: LessonStatus
  coins: number
  content?: LessonContent
  completedAt?: number
  /** 来源文件名 */
  sourceFile?: string
}

/** 关卡内容 */
export interface LessonContent {
  keyPoints: string[]
  explanation: string
  examples: ExampleItem[]
  quiz: QuizQuestion[]
}

/** 例题 */
export interface ExampleItem {
  question: string
  answer: string
  steps?: string[]
}

/** 测验题 */
/** 小测题目类型 */
export type QuizType = 'choice' | 'multi' | 'fill' | 'short'

/** 小测题目 */
export interface QuizQuestion {
  id: string
  type: QuizType
  question: string
  // 单选题
  options?: string[]
  correctIndex?: number
  // 多选题
  correctIndices?: number[]
  // 填空/简答题
  answer?: string
  acceptableAnswers?: string[]
  explanation: string
  /** 考点标题（用于重新生成题目） */
  examPointTitle?: string
}

/** 错题记录 */
export interface WrongQuestion {
  id: string
  courseId: string
  courseName: string
  lessonId: string
  lessonTitle: string
  question: string
  // 单选题
  options?: string[]
  correctIndex?: number
  selectedIndex?: number
  // 多选题
  correctIndices?: number[]
  selectedIndices?: number[]
  // 填空/简答题
  userAnswer?: string
  correctAnswer?: string
  // 通用
  quizType: QuizType
  explanation: string
  /** 考点标题 */
  examPointTitle: string
  /** 优先级 */
  priority: Priority
  /** 记录时间 */
  createdAt: number
  /** 是否已掌握（从错题本移除标记） */
  resolved: boolean
}

/** 聊天消息 */
export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  timestamp: number
  courseId?: string
}

// ===== Athena 智能助手类型 =====

/** Athena Ability (技能) */
export interface AthenaAbility {
  id: string
  name: string
  description: string
  /** Whether this ability was auto-discovered by Athena or manually added */
  autoGenerated: boolean
  createdAt: number
}

/** Memory type */
export type MemoryType = 'charter' | 'flow'

/** Athena Memory (记忆) */
export interface AthenaMemory {
  id: string
  type: MemoryType
  content: string
  /** For charter memory: the category (e.g. "personality", "rules", "preferences") */
  category?: string
  createdAt: number
  updatedAt: number
}

/** Athena task type */
export type AthenaTaskType = 'qa' | 'paper' | 'report' | 'summary' | 'plan'

/** Athena task */
export interface AthenaTask {
  id: string
  type: AthenaTaskType
  title: string
  status: 'active' | 'completed'
  createdAt: number
}

/** Athena export data (for device migration) */
export interface AthenaExportData {
  version: string
  exportedAt: number
  abilities: AthenaAbility[]
  memories: AthenaMemory[]
}

/** 学习进度 */
export interface Progress {
  totalLessons: number
  completedLessons: number
  chillCoins: number
  currentStreak: number
  lastStudyDate?: string
  /** 累计学习分钟数（用于学习时长 → Chill币 换算） */
  totalStudyMinutes?: number
}

/** 课程数据包（一个课程的完整数据） */
export interface CourseBundle {
  course: Course
  examPoints: ExamPoint[]
  lessons: Lesson[]
  progress: Progress
  rawText: string
  generatingLessons: boolean
  generationProgress: { current: number; total: number }
}

// ===== 本地账号类型 =====

/** 本地用户账号（离线运行，不与任何校园系统挂钩） */
export interface LocalAccount {
  /** 用户昵称 */
  name: string
  /** 自定义头像 emoji（可选） */
  avatar?: string
  /** 个性签名（可选） */
  bio?: string
  /** 创建时间戳 */
  createdAt: number
  /** 上次活跃时间戳 */
  lastActiveAt: number
}

// ===== 更新检查类型 =====

/** 更新状态 */
export type UpdateStatus = 'idle' | 'checking' | 'available' | 'not-available' | 'error'

/** 更新信息 */
export interface UpdateInfo {
  version: string
  releaseNotes: string
  downloadUrl: string
  releaseDate: string
  currentVersion: string
}

// ===== 教师工作台类型 =====

/** 教师生成的试题 */
export interface ExamQuestion {
  id: string
  type: 'choice' | 'multi' | 'fill' | 'short' | 'essay' | 'calculation'
  question: string
  options?: string[]
  correctIndex?: number
  correctIndices?: number[]
  answer?: string
  /** 计算题的解题步骤 */
  steps?: string[]
  acceptableAnswers?: string[]
  explanation: string
  difficulty: 'easy' | 'medium' | 'hard'
  points: number
}

/** 试卷配置 */
export interface ExamPaperConfig {
  title: string
  courseName: string
  totalPoints: number
  duration: number // minutes
  questionTypes: {
    choice: number
    multi: number
    fill: number
    short: number
    essay: number
    calculation: number
  }
}

/** 试卷 */
export interface ExamPaper {
  id: string
  config: ExamPaperConfig
  questions: ExamQuestion[]
  createdAt: number
}

// ===== 资源迁移类型 =====

/** 迁移结果 */
export interface MigrationResult {
  success: boolean
  migratedFiles: number
  totalSize: number
  errors: string[]
  /** 迁移后的新路径映射：旧路径 → 新路径 */
  pathMap: Record<string, string>
}

/** 文件信息（含路径） */
export interface FileInfo {
  path: string
  name: string
  ext: string
  size: number
}

// ===== Electron API 类型声明 =====

export interface ElectronAPI {
  openFileDialog: () => Promise<FileInfo[] | null>
  openImageDialog: () => Promise<FileInfo[] | null>
  openDirectoryDialog: () => Promise<string | null>
  readFileBuffer: (filePath: string) => Promise<ArrayBuffer>
  readTextFile: (filePath: string) => Promise<string>
  getUserDataPath: () => Promise<string>
  windowMinimize: () => void
  windowMaximize: () => void
  windowClose: () => void
  windowIsMaximized: () => Promise<boolean>
  onWindowMaximizeChange: (callback: (isMaximized: boolean) => void) => () => void
  // 专注模式
  enterFocusMode: () => void
  exitFocusMode: () => void
  focusExitConfirm: () => void
  isFullScreen: () => Promise<boolean>
  onFocusExited: (callback: () => void) => () => void
  platform: string
  // 应用版本
  getAppVersion: () => Promise<string>
  // 应用路径与存储占用
  getAppPaths: () => Promise<{ installPath: string; userDataPath: string; tempPath: string }>
  getStorageSize: () => Promise<number>
  // 在资源管理器中定位安装位置
  openInstallPath: () => Promise<void>
  // 更新检查
  checkForUpdates: () => Promise<UpdateInfo | null>
  // 自动更新：下载安装包并启动更新程序
  startUpdate: () => Promise<void>
  openExternalUrl: (url: string) => Promise<void>
  // 资源迁移
  migrateFiles: (filePaths: string[], targetDir: string, move?: boolean) => Promise<MigrationResult>
  getFileSize: (filePath: string) => Promise<number>
  fileExists: (filePath: string) => Promise<boolean>
}

declare global {
  interface Window {
    electronAPI?: ElectronAPI
  }
}
