import apiClient from './client';

export async function getAbilities(): Promise<{ abilities: any[] }> {
  const res = await apiClient.get('/athena/abilities');
  return res.data;
}

export async function addAbility(name: string, description: string, autoGenerated?: boolean): Promise<{ ability: any }> {
  const res = await apiClient.post('/athena/abilities', { name, description, autoGenerated });
  return res.data;
}

export async function deleteAbility(id: string): Promise<void> {
  await apiClient.delete(`/athena/abilities/${id}`);
}

export async function getMemories(): Promise<{ memories: any[] }> {
  const res = await apiClient.get('/athena/memories');
  return res.data;
}

export async function addMemory(type: string, content: string, category?: string): Promise<{ memory: any }> {
  const res = await apiClient.post('/athena/memories', { type, category, content });
  return res.data;
}

export async function updateMemory(id: string, data: { content?: string; category?: string }): Promise<void> {
  await apiClient.put(`/athena/memories/${id}`, data);
}

export async function deleteMemory(id: string): Promise<void> {
  await apiClient.delete(`/athena/memories/${id}`);
}