import { create } from 'zustand'
import { persist } from 'zustand/middleware'
import type { AthenaAbility, AthenaMemory, MemoryType, AthenaExportData } from '@types/index'

interface AthenaState {
  abilities: AthenaAbility[]
  memories: AthenaMemory[]
  
  // Abilities
  addAbility: (name: string, description: string) => void
  removeAbility: (id: string) => void
  updateAbility: (id: string, name: string, description: string) => void
  addAutoAbility: (name: string, description: string) => void
  
  // Memories
  addMemory: (type: MemoryType, content: string, category?: string) => void
  removeMemory: (id: string) => void
  updateMemory: (id: string, content: string) => void
  addAutoMemory: (content: string) => void
  clearFlowMemories: () => void
  
  // Charter memories (user-managed, agent cannot change)
  getCharterMemories: () => AthenaMemory[]
  getFlowMemories: () => AthenaMemory[]
  
  // Export / Import
  exportAthena: () => AthenaExportData
  importAthena: (data: AthenaExportData) => void
}

// Default charter memories (preset)
const DEFAULT_CHARTER_MEMORIES: AthenaMemory[] = [
  {
    id: 'charter-1',
    type: 'charter',
    category: 'identity',
    content: '你是 Athena，ChillPass 应用的智能学习助手。你的名字来源于希腊神话中的智慧女神雅典娜。你不仅是一个答疑工具，更是一个有温度、有思想的学伴。',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'charter-2',
    type: 'charter',
    category: 'rules',
    content: '你必须遵守以下规则：\n1. 回答简洁明了，用大白话解释复杂概念\n2. 结合学生的课件内容回答问题\n3. 鼓励学生，保持积极正面的态度\n4. 适当使用 Markdown 格式让回答更清晰\n5. 数学公式使用 LaTeX 语法（$...$ 或 $$...$$）\n6. 不得提供虚假信息，不确定时如实告知',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'charter-3',
    type: 'charter',
    category: 'personality',
    content: '你的性格特点：\n- 温和但严谨，像一位耐心的学长\n- 偶尔使用轻松幽默的语气，但不影响专业性\n- 会主动追问学生的理解程度\n- 在学生遇到困难时给予鼓励',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
]

export const useAthenaStore = create<AthenaState>()(
  persist(
    (set, get) => ({
      abilities: [],
      memories: DEFAULT_CHARTER_MEMORIES,

      addAbility: (name, description) => {
        const ability: AthenaAbility = {
          id: `ability-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          name,
          description,
          autoGenerated: false,
          createdAt: Date.now(),
        }
        set(state => ({ abilities: [...state.abilities, ability] }))
      },

      removeAbility: (id) => {
        set(state => ({ abilities: state.abilities.filter(a => a.id !== id) }))
      },

      updateAbility: (id, name, description) => {
        set(state => ({
          abilities: state.abilities.map(a =>
            a.id === id ? { ...a, name, description } : a
          ),
        }))
      },

      addAutoAbility: (name, description) => {
        // Avoid duplicates by name
        const existing = get().abilities.find(a => a.name === name)
        if (existing) return
        const ability: AthenaAbility = {
          id: `ability-auto-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          name,
          description,
          autoGenerated: true,
          createdAt: Date.now(),
        }
        set(state => ({ abilities: [...state.abilities, ability] }))
      },

      addMemory: (type, content, category) => {
        const memory: AthenaMemory = {
          id: `memory-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          type,
          content,
          category,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        }
        set(state => ({ memories: [...state.memories, memory] }))
      },

      removeMemory: (id) => {
        set(state => ({ memories: state.memories.filter(m => m.id !== id) }))
      },

      updateMemory: (id, content) => {
        set(state => ({
          memories: state.memories.map(m =>
            m.id === id ? { ...m, content, updatedAt: Date.now() } : m
          ),
        }))
      },

      addAutoMemory: (content) => {
        // Avoid duplicates by content similarity
        const existing = get().memories.find(m => 
          m.type === 'flow' && m.content === content
        )
        if (existing) return
        const memory: AthenaMemory = {
          id: `memory-flow-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
          type: 'flow',
          content,
          createdAt: Date.now(),
          updatedAt: Date.now(),
        }
        set(state => ({ memories: [...state.memories, memory] }))
      },

      clearFlowMemories: () => {
        set(state => ({
          memories: state.memories.filter(m => m.type === 'charter'),
        }))
      },

      getCharterMemories: () => {
        return get().memories.filter(m => m.type === 'charter')
      },

      getFlowMemories: () => {
        return get().memories.filter(m => m.type === 'flow')
      },

      exportAthena: () => {
        return {
          version: '1.0',
          exportedAt: Date.now(),
          abilities: get().abilities,
          memories: get().memories,
        }
      },

      importAthena: (data) => {
        set({
          abilities: data.abilities || [],
          memories: data.memories || DEFAULT_CHARTER_MEMORIES,
        })
      },
    }),
    {
      name: 'athena-storage',
    }
  )
)
