# -*- coding: utf-8 -*-
# i18n 收尾批量替换：剩余页面 / 组件 / 服务层 / stores / electronMock
import io

REPLACEMENTS = {
'src/pages/AIChatPage.tsx': [
("<span>{ocrProgress || '识别中...'}</span>", "<span>{ocrProgress || t('athena.ocrFallback')}</span>"),
("<span className={styles.memoryCategory}>{m.category || '自定义'}</span>", "<span className={styles.memoryCategory}>{m.category || t('athena.memCategoryCustom')}</span>"),
("<p className={styles.emptyHint}>暂无技能，Athena 会在对话中自动发现新技能</p>", "<p className={styles.emptyHint}>{t('athena.noAbilitiesHint')}</p>"),
("{a.autoGenerated && <span className={styles.autoTag}>自动发现</span>}", "{a.autoGenerated && <span className={styles.autoTag}>{t('athena.autoTag')}</span>}"),
("<h4>宪章记忆</h4>", "<h4>{t('athena.charterMemory')}</h4>"),
("<p className={styles.memoryHint}>用户管理，Athena 必须遵守，不能自行修改</p>", "<p className={styles.memoryHint}>{t('athena.charterMemoryHint')}</p>"),
("<button onClick={() => { updateMemory(m.id, editText); setEditingId(null) }}>保存</button>", "<button onClick={() => { updateMemory(m.id, editText); setEditingId(null) }}>{t('common.save')}</button>"),
("<button onClick={() => setEditingId(null)}>取消</button>", "<button onClick={() => setEditingId(null)}>{t('common.cancel')}</button>"),
("<h4>流动记忆</h4>", "<h4>{t('athena.flowMemory')}</h4>"),
("<p className={styles.memoryHint}>Athena 自动管理，记录用户偏好和学习习惯</p>", "<p className={styles.memoryHint}>{t('athena.flowMemoryHint')}</p>"),
("<p className={styles.emptyHint}>暂无流动记忆，Athena 会在对话中自动积累</p>", "<p className={styles.emptyHint}>{t('athena.noFlowMemoriesHint')}</p>"),
],
'src/pages/Dashboard.tsx': [
("""const priorityLabel: Record<Priority, string> = {
  must: '必考',
  high: '高频',
  know: '了解',
}

""", ""),
('title="从 JSON 文件导入已导出的课程"', "title={t('dashboard.importCourseTip')}"),
],
'src/pages/WrongBookPage.tsx': [
("<h1 className={styles.title}>错题本</h1>", "<h1 className={styles.title}>{t('wrongbook.title')}</h1>"),
("<p className={styles.subtitle}>按课程归类，逐个击破</p>", "<p className={styles.subtitle}>{t('wrongbook.subtitle')}</p>"),
],
'src/pages/SettingsPage.tsx': [
("""    const confirmed = window.confirm(
      `发现新版本 v${updateInfo.version}（当前 v${updateInfo.currentVersion}），是否立即下载并更新？\\n\\n更新过程中应用将自动关闭，完成后自动重新启动。`,
    )""",
"""    const confirmed = window.confirm(
      t('settings.updateConfirm')
        .replace('{version}', updateInfo.version)
        .replace('{current}', updateInfo.currentVersion),
    )"""),
],
'src/App.tsx': [
("import styles from './App.module.css'", "import styles from './App.module.css'\nimport { useT } from './i18n'"),
("""export default function App() {
  const location = useLocation()
  const ensureAccount = useAuthStore(s => s.ensureAccount)

  useEffect(() => {
    document.title = 'ChillPass — 期末冲刺助手'
    // 首次使用自动创建本地账号
    ensureAccount()
  }, [])""",
"""export default function App() {
  const location = useLocation()
  const ensureAccount = useAuthStore(s => s.ensureAccount)
  const t = useT()

  useEffect(() => {
    document.title = t('app.docTitle')
    // 首次使用自动创建本地账号
    ensureAccount()
  }, [t])"""),
],
'src/components/layout/TitleBar.tsx': [
('alt="ChillPass 用户交流群二维码"', "alt={t('titlebar.helpQrAlt')}"),
],
'src/pages/settings/ApiSettings.tsx': [
("<h1 className={styles.title}>API 配置</h1>", "<h1 className={styles.title}>{t('settings.api')}</h1>"),
("<p className={styles.subtitle}>接入 DeepSeek 大模型，用于提炼考点与生成课程</p>", "<p className={styles.subtitle}>{t('api.subtitle')}</p>"),
(""">
              智谱 GLM
            </button>""",
""">
              {t('api.providerZhipu')}
            </button>"""),
("""              {PROVIDER_MODELS[provider].map(m => (
                <option key={m.id} value={m.id}>{m.label}</option>
              ))}""",
"""              {PROVIDER_MODELS[provider].map(m => (
                <option key={m.id} value={m.id}>{t(m.labelKey)}</option>
              ))}"""),
],
'src/pages/settings/StorageSettings.tsx': [
("<h1 className={styles.title}>存储与迁移</h1>", "<h1 className={styles.title}>{t('settings.storage')}</h1>"),
("<h2 className={styles.cardTitle}>资源存储位置</h2>", "<h2 className={styles.cardTitle}>{t('storage.resLocation')}</h2>"),
("<span className={styles.pathBadge}>默认</span>", "<span className={styles.pathBadge}>{t('storage.defaultBadge')}</span>"),
("<h2 className={styles.cardTitle}>资源迁移</h2>", "<h2 className={styles.cardTitle}>{t('storage.migration')}</h2>"),
("<label className={styles.label}>课件文件清单</label>", "<label className={styles.label}>{t('storage.fileList')}</label>"),
("<span>共 {allFiles.length} 个文件</span>", "<span>{t('storage.totalFiles').replace('{count}', String(allFiles.length))}</span>"),
("<span>总大小 {formatSize(totalSize)}</span>", "<span>{t('storage.totalSizeLabel').replace('{size}', formatSize(totalSize))}</span>"),
("<span>{missingCount} 个文件缺失</span>", "<span>{t('storage.filesMissing').replace('{count}', String(missingCount))}</span>"),
("<span>正在检查文件...</span>", "<span>{t('storage.checkingFiles')}</span>"),
("<label className={styles.label}>目标目录</label>", "<label className={styles.label}>{t('storage.targetDir')}</label>"),
("<label className={styles.label}>迁移模式</label>", "<label className={styles.label}>{t('storage.modeLabel')}</label>"),
("<span>复制</span>", "<span>{t('storage.modeCopy')}</span>"),
("<span>移动</span>", "<span>{t('storage.modeMove')}</span>"),
("<span>正在迁移文件... {Math.round(progress)}%</span>", "<span>{t('storage.migratingProgress').replace('{percent}', String(Math.round(progress)))}</span>"),
("<div>成功迁移：{migrationResult.migratedFiles} 个文件</div>", "<div>{t('storage.migratedCount').replace('{count}', String(migrationResult.migratedFiles))}</div>"),
("<div>迁移总量：{formatSize(migrationResult.totalSize)}</div>", "<div>{t('storage.migratedTotalSize').replace('{size}', formatSize(migrationResult.totalSize))}</div>"),
("<div style={{ marginTop: 4 }}>目标目录：{targetDir}</div>", "<div style={{ marginTop: 4 }}>{t('storage.targetDirResult').replace('{dir}', targetDir)}</div>"),
],
'src/components/AccountLogin.tsx': [
("import { useAuthStore } from '@stores/authStore'", "import { useAuthStore } from '@stores/authStore'\nimport { useT } from '../i18n'"),
("  const login = useAuthStore(s => s.login)", "  const login = useAuthStore(s => s.login)\n  const t = useT()"),
("setError('请输入昵称')", "setError(t('account.nameRequired'))"),
("<h2 className={styles.modalTitle}>创建本地账号</h2>", "<h2 className={styles.modalTitle}>{t('account.createTitle')}</h2>"),
("<p className={styles.modalSubtitle}>账号信息仅保存在本机，离线运行，无需联网</p>", "<p className={styles.modalSubtitle}>{t('account.modalSubtitle')}</p>"),
("aria-label=\"关闭\"", "aria-label={t('account.close')}"),
("""            <span>
              当前为本地离线账号，所有信息仅保存在本机浏览器中，不会上传到任何服务器。
            </span>""",
"""            <span>
              {t('account.offlineHintLogin')}
            </span>"""),
("<label className={styles.label}>昵称 *</label>", "<label className={styles.label}>{t('account.nameLabel')}</label>"),
("placeholder=\"请输入昵称\"", "placeholder={t('account.namePlaceholder')}"),
("<label className={styles.label}>头像</label>", "<label className={styles.label}>{t('account.avatarLabel')}</label>"),
("aria-label={`选择头像 ${emoji}`}", "aria-label={t('account.pickAvatar').replace('{emoji}', emoji)}"),
("<label className={styles.label}>个性签名</label>", "<label className={styles.label}>{t('account.bioLabel')}</label>"),
("placeholder=\"一句话介绍自己（可选）\"", "placeholder={t('account.bioPlaceholder')}"),
("""              取消
            </button>""",
"""              {t('common.cancel')}
            </button>"""),
("""              创建账号
            </button>""",
"""              {t('account.createBtn')}
            </button>"""),
],
'src/components/AccountEditor.tsx': [
("import { useAuthStore } from '@stores/authStore'", "import { useAuthStore } from '@stores/authStore'\nimport { useT } from '../i18n'"),
("  const updateAccount = useAuthStore(s => s.updateAccount)", "  const updateAccount = useAuthStore(s => s.updateAccount)\n  const t = useT()"),
("setError('请输入昵称')", "setError(t('account.nameRequired'))"),
("<h2 className={styles.modalTitle}>编辑个人资料</h2>", "<h2 className={styles.modalTitle}>{t('account.editTitle')}</h2>"),
("<p className={styles.modalSubtitle}>账号信息仅保存在本机，离线运行，无需联网</p>", "<p className={styles.modalSubtitle}>{t('account.modalSubtitle')}</p>"),
("aria-label=\"关闭\"", "aria-label={t('account.close')}"),
("""            <span>
              当前为本地离线账号，所有信息仅保存在本机浏览器中，不会上传到任何服务器。可在设置中导出账号信息到新设备。
            </span>""",
"""            <span>
              {t('account.offlineHintEditor')}
            </span>"""),
("<label className={styles.label}>昵称 *</label>", "<label className={styles.label}>{t('account.nameLabel')}</label>"),
("placeholder=\"请输入昵称\"", "placeholder={t('account.namePlaceholder')}"),
("<label className={styles.label}>头像</label>", "<label className={styles.label}>{t('account.avatarLabel')}</label>"),
("aria-label={`选择头像 ${emoji}`}", "aria-label={t('account.pickAvatar').replace('{emoji}', emoji)}"),
("<label className={styles.label}>个性签名</label>", "<label className={styles.label}>{t('account.bioLabel')}</label>"),
("placeholder=\"一句话介绍自己（可选）\"", "placeholder={t('account.bioPlaceholder')}"),
("""              取消
            </button>""",
"""              {t('common.cancel')}
            </button>"""),
("""              保存
            </button>""",
"""              {t('common.save')}
            </button>"""),
],
'src/stores/settingsStore.ts': [
("import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'", "import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\nimport type { TranslationKey } from '../i18n/translations'"),
("""export const PROVIDER_MODELS: Record<AIProvider, { id: string; label: string }[]> = {
  deepseek: [
    { id: 'deepseek-chat', label: 'deepseek-chat（通用对话，速度快）' },
    { id: 'deepseek-reasoner', label: 'deepseek-reasoner（深度推理，更精准）' },
  ],
  zhipu: [
    { id: 'glm-5.3-flash', label: 'glm-5.3-flash（高速响应，性价比高）' },
    { id: 'glm-5.3', label: 'glm-5.3（旗舰模型，能力更强）' },
  ],
}""",
"""export const PROVIDER_MODELS: Record<AIProvider, { id: string; labelKey: TranslationKey }[]> = {
  deepseek: [
    { id: 'deepseek-chat', labelKey: 'model.deepseekChat' },
    { id: 'deepseek-reasoner', labelKey: 'model.deepseekReasoner' },
  ],
  zhipu: [
    { id: 'glm-5.3-flash', labelKey: 'model.glmFlash' },
    { id: 'glm-5.3', labelKey: 'model.glm53' },
  ],
}"""),
],
'src/stores/authStore.ts': [
("import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\nimport type { LocalAccount } from '@types/index'", "import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\nimport type { LocalAccount } from '@types/index'\nimport { translate } from '../i18n'\nimport { useLanguageStore } from '@stores/languageStore'"),
("    name: '学习者',", "    name: translate(useLanguageStore.getState().language, 'account.defaultName'),"),
],
'src/stores/courseStore.ts': [
("import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\nimport { nanoid } from 'nanoid'", "import { create } from 'zustand'\nimport { persist } from 'zustand/middleware'\nimport { nanoid } from 'nanoid'\nimport { translate } from '../i18n'\nimport { useLanguageStore } from '@stores/languageStore'"),
("          throw new Error('Chill币不足，需要 ' + cost + ' 枚')", "          throw new Error(translate(useLanguageStore.getState().language, 'store.insufficientCoins').replace('{cost}', String(cost)))"),
],
'src/services/deepseek.ts': [
("""/** 服务层抛错的本地化文本 */
function serviceError(key: string): Error {
  return new Error(translate(useLanguageStore.getState().language, key))
}""",
"""/** 服务层抛错的本地化文本 */
function serviceError(key: string): Error {
  return new Error(serviceText(key))
}

/** 服务层提示文案（当前语言） */
function serviceText(key: string, map?: Record<string, string>): string {
  let msg = translate(useLanguageStore.getState().language, key)
  for (const [k, v] of Object.entries(map ?? {})) msg = msg.replace(`{${k}}`, v)
  return msg
}

/** 服务层抛错的本地化文本（带占位符） */
function serviceErrorFmt(key: string, map: Record<string, string>): Error {
  return new Error(serviceText(key, map))
}"""),
("        throw new Error(`DeepSeek API 错误: ${response.status} - ${error}`)", "        throw serviceErrorFmt('service.apiError', { code: String(response.status), msg: error })"),
("    throw new Error(`DeepSeek API 错误: ${response.status} - ${error}`)", "    throw serviceErrorFmt('service.apiError', { code: String(response.status), msg: error })"),
("  throw new Error('请求失败，已重试 ' + maxRetries + ' 次')", "  throw serviceErrorFmt('service.retriesExhausted', { count: String(maxRetries) })"),
("    throw new Error('关卡内容生成失败，请重试')", "    throw serviceError('service.genLessonFailed')"),
("    throw new Error('题目重新生成失败，请重试')", "    throw serviceError('service.regenQuestionFailed')"),
("    return { correct: true, feedback: '回答完全正确！' }", "    return { correct: true, feedback: serviceText('service.answerCorrectAll') }"),
("      return { correct: true, feedback: '回答正确，包含了所有关键点！' }", "      return { correct: true, feedback: serviceText('service.answerCorrect') }"),
("""      return {
        correct: false,
        feedback: `部分正确（命中 ${matchedCount}/${acceptableAnswers.length} 个关键点），但还不够完整。参考答案：${correctAnswer}`,
      }""",
"""      return {
        correct: false,
        feedback: serviceText('service.answerPartial', {
          matched: String(matchedCount),
          total: String(acceptableAnswers.length),
          answer: correctAnswer,
        }),
      }"""),
("      feedback: parsed.feedback || (parsed.correct ? '回答正确！' : '回答不正确'),", "      feedback: parsed.feedback || serviceText(parsed.correct ? 'service.answerFeedbackOk' : 'service.answerFeedbackBad'),"),
("      feedback: `无法自动评阅，参考答案：${correctAnswer}`,", "      feedback: serviceText('service.answerUngradeable', { answer: correctAnswer }),"),
],
'src/services/fileParser.ts': [
("""/**
 * 文件解析服务
 * 支持 PDF、PPTX、DOCX、DOC、TXT、MD
 */""",
"""/**
 * 文件解析服务
 * 支持 PDF、PPTX、DOCX、DOC、TXT、MD
 */
import { translate } from '../i18n'
import { useLanguageStore } from '@stores/languageStore'

/** 解析服务抛错的本地化文本 */
function parseError(key: string, map?: Record<string, string>): Error {
  let msg = translate(useLanguageStore.getState().language, key)
  for (const [k, v] of Object.entries(map ?? {})) msg = msg.replace(`{${k}}`, v)
  return new Error(msg)
}"""),
("throw new Error(`不支持的文件格式: ${ext}`)", "throw parseError('parse.unsupportedFormat', { ext })"),
("throw new Error('文件 API 不可用')", "throw parseError('parse.apiUnavailable')", 5),
("throw new Error('无法读取 Word 文档内容（缺少 document.xml），请确认文件为有效的 .docx')", "throw parseError('parse.docxNoXml')"),
("throw new Error('未能从 Word 文档中提取到文本内容')", "throw parseError('parse.docxNoText')"),
("throw new Error('该文件实为 RTF 格式，请用 Word 另存为 .docx 后重新导入')", "throw parseError('parse.docIsRtf')"),
("throw new Error('无法读取 Word 文档内容（WordDocument 流缺失）')", "throw parseError('parse.docNoStream')"),
("throw new Error('该文件不是有效的 Word 97-2003 文档')", "throw parseError('parse.docInvalid')"),
("throw new Error('未能从 DOC 文件中提取到有效文本，建议用 Word 将文件另存为 .docx 后重新导入')", "throw parseError('parse.docNoText')"),
("throw new Error('该文件不是有效的 Word 97-2003 文档（缺少 OLE 复合文档头）')", "throw parseError('parse.docInvalidOle')"),
],
'src/services/imageService.ts': [
("""/**
 * 图片识别服务
 * 在渲染进程中使用 tesseract.js，所有资源（worker、core、lang）从 CDN 加载
 * 彻底避免 Electron 打包后本地 worker 路径找不到的问题
 */""",
"""/**
 * 图片识别服务
 * 在渲染进程中使用 tesseract.js，所有资源（worker、core、lang）从 CDN 加载
 * 彻底避免 Electron 打包后本地 worker 路径找不到的问题
 */
import { translate } from '../i18n'
import { useLanguageStore } from '@stores/languageStore'

/** 图片识别抛错的本地化文本 */
function imgError(key: string, map?: Record<string, string>): Error {
  let msg = translate(useLanguageStore.getState().language, key)
  for (const [k, v] of Object.entries(map ?? {})) msg = msg.replace(`{${k}}`, v)
  return new Error(msg)
}"""),
("reject(new Error('图片识别超时（60秒），请检查网络连接后重试'))", "reject(imgError('img.ocrTimeout'))"),
("throw new Error(`图片识别失败: ${err instanceof Error ? err.message : '未知错误'}`)", "throw imgError('img.ocrFailed', { msg: err instanceof Error ? err.message : translate(useLanguageStore.getState().language, 'common.unknownError') })"),
("throw new Error('无法读取文件，文件 API 不可用')", "throw imgError('img.apiUnavailable')"),
],
'src/services/browserFileStore.ts': [
("""/**
 * 浏览器文件存储服务
 * 使用 IndexedDB 持久化用户上传的课件文件内容
 * 替代 Electron 的文件系统访问能力
 */""",
"""/**
 * 浏览器文件存储服务
 * 使用 IndexedDB 持久化用户上传的课件文件内容
 * 替代 Electron 的文件系统访问能力
 */
import { translate } from '../i18n'
import { useLanguageStore } from '@stores/languageStore'"""),
("reject(new Error(`文件未找到: ${id}`))", "reject(new Error(translate(useLanguageStore.getState().language, 'service.fileNotFound').replace('{id}', id)))"),
],
'src/utils/electronMock.ts': [
("""import {
  storeFile,
  readFileBuffer,
  readTextFile,
  fileExists,
  getFileSize,
  getStorageSize as getIDBStorageSize,
} from '@services/browserFileStore'""",
"""import {
  storeFile,
  readFileBuffer,
  readTextFile,
  fileExists,
  getFileSize,
  getStorageSize as getIDBStorageSize,
} from '@services/browserFileStore'
import { translate } from '../i18n'
import { useLanguageStore } from '@stores/languageStore'

/** 浏览器 Mock 提示文案（当前语言） */
function mockText(key: string, map?: Record<string, string>): string {
  let msg = translate(useLanguageStore.getState().language, key)
  for (const [k, v] of Object.entries(map ?? {})) msg = msg.replace(`{${k}}`, v)
  return msg
}"""),
("window.prompt('浏览器模式下不支持选择目录，文件将存储在浏览器 IndexedDB 中')", "window.prompt(mockText('mock.dirDialogPrompt'))"),
("return '浏览器 IndexedDB 存储'", "return mockText('mock.userDataPath')"),
("if (window.confirm('确定要关闭应用吗？')) {", "if (window.confirm(mockText('mock.closeConfirm'))) {"),
("if (window.confirm('退出专注模式？')) {", "if (window.confirm(mockText('mock.focusExitConfirm'))) {"),
("""      return {
        installPath: '未安装（网页预览模式）',
        userDataPath: '浏览器 IndexedDB / localStorage',
        tempPath: '浏览器内存',
      }""",
"""      return {
        installPath: mockText('mock.installPath'),
        userDataPath: mockText('mock.userDataBrowser'),
        tempPath: mockText('mock.tempPath'),
      }"""),
("window.alert('当前为网页预览模式，未安装应用，无法定位安装位置')", "window.alert(mockText('mock.installPathAlert'))"),
("releaseNotes: data.releaseNotes || '暂无更新说明',", "releaseNotes: data.releaseNotes || mockText('mock.noReleaseNotes'),"),
("const releaseNotes = release.body || '暂无更新说明'", "const releaseNotes = release.body || mockText('mock.noReleaseNotes')"),
("""          throw new Error(
            `无法连接更新服务器，请检查网络后重试（${err instanceof Error ? err.message : '未知错误'}）`,
          )""",
"""          throw new Error(
            mockText('mock.updateServerUnreachable', {
              msg: err instanceof Error ? err.message : mockText('common.unknownError'),
            }),
          )"""),
],
}

total_missing = 0
for path, pairs in REPLACEMENTS.items():
    with io.open(path, 'r', encoding='utf-8') as f:
        c = f.read()
    missing = []
    for pair in pairs:
        old, new = pair[0], pair[1]
        expected = pair[2] if len(pair) > 2 else 1
        found = c.count(old)
        if found == 0:
            missing.append(old[:80])
            continue
        c = c.replace(old, new)
        if expected > 1 and found != expected:
            print(f'WARN {path}: expected {expected} occurrences, found {found}: {old[:60]!r}')
    if missing:
        total_missing += len(missing)
        print(f'MISSING in {path}: {len(missing)}')
        for m in missing:
            print('   ', repr(m))
    else:
        with io.open(path, 'w', encoding='utf-8', newline='') as f:
            f.write(c)
        print(f'OK {path}: {len(pairs)} replacements')

print('DONE, missing =', total_missing)
